# This is a basic workflow to help you get started with Actions

name: Upload

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - master
      - new-deployment

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0

      - name: install mdbook
        run: |
          cargo install mdbook
          mdbook build --dest-dir ../docs.webxdc.org
      - name: Upload
        uses: horochx/deploy-via-scp@v1.0.1
        with:
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          host: "delta.chat"
          port: 22
          local: "docs.webxdc.org"
          remote: "/var/www/html/"
